'use client'

import Link from 'next/link'
import Image from 'next/image'
import { Suspense, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { Phone, MessageCircle } from 'lucide-react'
import { faqs, nav, site, subjects, zones, whatsappLink, telLink } from '@/lib/site-config'

export function Header() {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><div className="container header-inner"><Link href="/" className="brand" aria-label="Rajesh Home Tuitions home"><Image src={site.logo} alt="Rajesh Home Tuitions logo" width={72} height={62} priority /><span><b>RAJESH</b><small>HOME TUITIONS</small></span></Link><nav className={`nav ${open ? 'nav-open' : ''}`}>{nav.map(item => <Link key={item.href} href={item.href} onClick={() => setOpen(false)}>{item.label}</Link>)}<Link className="button button-small" href="/join-parent" onClick={() => setOpen(false)}>Find a tutor</Link></nav><button className="menu-button" aria-label="Toggle menu" aria-expanded={open} onClick={() => setOpen(!open)}><span /><span /><span /></button></div></header>
}

export function ContactStrip() { return <section className="contact-section" aria-label="Contact Rajesh Home Tuitions"><div className="container"><h2 className="contact-section-heading">Contact Us</h2><div className="contact-strip-inner"><a href={telLink}><span>Call</span>{site.phoneDisplay}</a><a href={whatsappLink('Hi Rajesh Home Tuitions, I would like to enquire about home tuition.')}><span>WhatsApp</span>{site.phoneDisplay}</a><a href={site.mapUrl} target="_blank" rel="noreferrer"><span>Location</span>{site.location}</a></div></div></section> }

export function LocationMap() { return <section className="section map-section"><div className="container"><div className="map-heading"><div><p className="eyebrow">VISIT OUR AREA</p><h2>Find Rajesh Home Tuitions</h2><p>{site.location}</p></div><a className="button" href={site.mapUrl} target="_blank" rel="noreferrer">Open in Google Maps</a></div><div className="map-frame"><iframe title="Rajesh Home Tuitions location map" src="https://www.google.com/maps?q=F9RW%2BVC%20Hyderabad%2C%20Telangana&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div></section> }

export function Footer() { return <footer className="footer"><div className="container footer-grid"><div><Link href="/" className="brand footer-brand"><Image src={site.logo} alt="" width={62} height={54} /><span><b>RAJESH</b><small>HOME TUITIONS</small></span></Link><p>Focused learning. Personal attention. Better confidence.</p></div><div><h3>Explore</h3>{nav.slice(1, 5).map(n => <Link key={n.href} href={n.href}>{n.label}</Link>)}</div><div><h3>Get in touch</h3><a href={telLink}>{site.phoneDisplay}</a><a href={whatsappLink()}>WhatsApp us</a><a href={site.mapUrl} target="_blank" rel="noreferrer">Hyderabad, Telangana</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Rajesh Home Tuitions</span><span>Learning starts with the right support.</span></div></footer> }

export function PageHero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="page-hero"><div className="container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="hero-copy">{text}</p></div></section> }
export function SectionHeading({ eyebrow, title, text }: { eyebrow?: string; title: string; text?: string }) { return <div className="section-heading">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{text && <p>{text}</p>}</div> }
export function FloatingActions() { return <div className="floating-actions"><a className="float-whatsapp" href={whatsappLink('Hi Rajesh Home Tuitions, I would like to enquire about home tuition.')} aria-label="WhatsApp Us" title="WhatsApp Us" target="_blank" rel="noreferrer"><MessageCircle aria-hidden="true" size={20} />WhatsApp</a><a className="float-call" href={telLink} aria-label="Call Now" title="Call Now"><Phone aria-hidden="true" size={20} />Call</a></div> }

function EnquiryFormContent({ tutor = false }: { tutor?: boolean }) {
  const params = useSearchParams(); const [sent, setSent] = useState(false); const [area, setArea] = useState(params.get('area') || '')
  if (sent) return <div className="success-box"><span className="success-mark">✓</span><h3>Thank you for reaching out.</h3><p>Your enquiry is ready to send. We look forward to speaking with you.</p><button className="button button-outline" onClick={() => setSent(false)}>Start another enquiry</button></div>
  return <form className="enquiry-form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const message = `${tutor ? 'Tutor application' : 'Home tuition enquiry'}%0AName: ${data.get('name')}%0APhone: ${data.get('phone')}%0A${tutor ? `Experience: ${data.get('experience')}` : `Student class: ${data.get('class')}%0ASubject: ${data.get('subject')}%0AArea: ${data.get('area')}`}`; window.open(whatsappLink(decodeURIComponent(message)), '_blank', 'noopener,noreferrer'); setSent(true) }}><div className="form-row"><label>Name<input name="name" required placeholder={tutor ? 'Your full name' : 'Parent or guardian name'} /></label><label>Phone<input name="phone" type="tel" required placeholder="Your phone number" /></label></div>{tutor ? <label>Teaching experience<input name="experience" required placeholder="Subjects, classes, and years of experience" /></label> : <div className="form-row"><label>Student class<select name="class" required defaultValue=""><option value="" disabled>Select class</option>{['Class 1–5','Class 6–8','Class 9–10','Class 11–12'].map(x => <option key={x}>{x}</option>)}</select></label><label>Subject<select name="subject" required defaultValue=""><option value="" disabled>Select subject</option>{subjects.map(x => <option key={x}>{x}</option>)}</select></label></div>} {!tutor && <label>Area<input name="area" required value={area} onChange={e => setArea(e.target.value)} placeholder="Your Hyderabad area" /></label>}<label>Message<textarea name="message" rows={4} placeholder={tutor ? 'Tell us a little about yourself' : 'Preferred days, timings, or anything we should know'} /></label><button className="button" type="submit">Send enquiry on WhatsApp</button><p className="form-note">We’ll use your details only to respond to this enquiry.</p></form>
}

export function EnquiryForm({ tutor = false }: { tutor?: boolean }) { return <Suspense fallback={<div className="enquiry-form" aria-busy="true">Loading enquiry form…</div>}><EnquiryFormContent tutor={tutor} /></Suspense> }

export function FAQList() { const [active, setActive] = useState<number | null>(0); return <div className="faq-list">{faqs.map((f, i) => <div className="faq-item" key={f.q}><button aria-expanded={active === i} onClick={() => setActive(active === i ? null : i)}><span>{f.q}</span><b>{active === i ? '−' : '+'}</b></button>{active === i && <p>{f.a}</p>}</div>)}</div> }
export function ZoneList() { const [query, setQuery] = useState(''); const filtered = zones.filter(z => z.toLowerCase().includes(query.toLowerCase())); return <div><input className="zone-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search your area" aria-label="Search service zones" /><div className="zone-list">{filtered.map(z => <Link href={`/contact?area=${encodeURIComponent(z)}`} key={z}>{z}<span>→</span></Link>)}</div>{filtered.length === 0 && <p className="muted">We may still be able to help. Call us to check your area.</p>}</div> }

export function SiteShell({ children }: { children: React.ReactNode }) { return <><Header />{children}<ContactStrip /><Footer /><FloatingActions /></> }
